<script>
	import { onMount } from 'svelte';
	import Modal from './modal.svelte';
	let quote = '';
	export const ssr = false;

	let showModal = false;

	const getData = async () => {
		const response = await fetch('https://api.kanye.rest');
		if (response.ok) {
			const json = await response.json();
			quote = undefined;
			quote = json.quote;
		} else {
			console.error('Error:', response.status);
		}
	};

	onMount(() => {
		getData();
	});
</script>

<section>
	<p class="title">Click Kanye to get a Quote</p>
</section>

<main>
	<div class="container">
		<!-- svelte-ignore a11y-click-events-have-key-events -->
		<!-- svelte-ignore a11y-no-noninteractive-element-interactions -->
		<img src="../../kanye1.png" alt="Kanye West" on:click={getData} />
		<div class="quote">
			<blockquote>
				<h2>
					{quote}
				</h2>
				<footer>
					<cite>- Kanye West </cite>
				</footer>
			</blockquote>
		</div>
	</div>
	<section>
		<button on:click={() => (showModal = true)}> AUTHOR'S DISCLAIMER </button>

		<Modal bind:showModal>
			<h2 slot="header">Disclaimer</h2>

			<p>
				This site utilizes the kanye.rest API for the purpose of demonstrating API integration and
				does not endorse or represent any views, opinions, or statements made by Kanye West. The
				quotes generated by this tool are purely illustrative and not indicative of the site owner's
				personal views or values. Use of this quote generator should not be interpreted as support
				or approval of Kanye West's actions or statements, which can often be controversial and
				divisive. This tool is provided for its humor and technical demonstration value only.
			</p>
		</Modal>
	</section>
</main>

<style>
	.title {
		text-align: center;
	}
	.container {
		display: flex;
		align-items: center;
		justify-content: space-between;
	}
	.quote {
		flex-grow: 1;
		text-align: center;
	}
	img {
		width: 30%;
		height: 30%;
		cursor: pointer;
		padding: 1rem;
	}

	img:hover {
		transform: scale(1.2);
	}
</style>
